name: py36tgsa

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - ase
  - cudatoolkit=10.2
  - googledrivedownloader
  - h5py
  - jinja2
  - networkx
  - numba
  - numpy
  - pandas
  - pip
  - python=3.6
  - python-louvain
  - pytorch=1.6.0
  - rdflib
  - requests
  - scikit-learn
  - scipy
  - torchaudio
  - torchvision
  - tqdm
